{% set name = "mira-moods" %}
{% set version = "1.9.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mira-moods-{{ version }}.tar.gz
  sha256: e694e37c7487286801bffcda3e0576157960007919dd5ceb8b5a1626dc2968e1

build:
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - MOODS
  commands:
    - pip check
    - moods-dna.py -h
  requires:
    - pip

about:
  home: https://www.cs.helsinki.fi/group/pssmfind/
  summary: 'MOODS: Motif Occurrence Detection Suite'
  license: MIT AND GPL-3.0
  license_file:
    - COPYING.BIOPYTHON
    - COPYING.GPLv3

extra:
  recipe-maintainers:
    - AllenWLynch
